# bgp_ports:
#   - Ethernet120
#   - Ethernet124

# breakouts:
#   Ethernet0: 4x25G
#   Ethernet120: 1x100G[40G]

# docker_routing_config_mode: split
# frr_mgmt_framework_config: false

# interconnects:
#   mpls:
#     vni: 104010
#     vrf: VrfMpls

# hostname: leaf01
# lldp_hello_time: 10
# loopback_address: 10.7.7.7

# mclag:
#   keepalive_vlan: 1000
#   member_port_channels:
#     - 11
#   peer_ip: 192.168.255.1
#   peer_link: PortChannel01
#   source_ip: 192.168.255.2
#   system_mac: aa:aa:aa:aa:aa:aa

# mgmtif_gateway: 10.7.10.1
# mgmtif_ip: 10.7.10.2
# mgmt_vrf: false

# ntpservers:
#   - 0.europe.pool.ntp.org

# portchannels:
#   - number: "01"
#     mtu: 1500
#     fallback: true
#     members:
#       - Ethernet4

# portchannels_default_mtu: 9000

# ports:
#   - name: Ethernet0
#     ips:
#       - 10.4.3.2
#     fec: rs
#     mtu: 1500
#     speed: 25000
#     vrf: VrfMpls

# ports_default_fec: none
# ports_default_mtu: 9000

# sag:
#   mac: bb:bb:bb:bb:bb:bb

# ssh_sourceranges:
#   - 10.1.23.1/30

# vlans:
#   - id: 4000
#     dhcp_servers:
#       - 10.9.8.7
#     ip: 10.9.7.0
#     sag: true
#     tagged_ports:
#       - PortChannel01
#     untagged_ports:
#       - PortChannel11
#     vrf: Vrf45

# vlan_members: true

# vteps:
#   - vni: 103999
#     vlan: Vlan3999
