name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: -p bugs -p unused --timeout=3m

      - name: Test
        run: make test test-generate

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 make build
          GOOS=linux GOARCH=arm64 make build
        if: ${{ github.event_name == 'release' }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: bin/*
        if: ${{ github.event_name == 'release' }}
